<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="5TS206424426L7" name="com.nbcuni.test.nbcidx.member.undelete.brands.TC5085_MemberUndelete_Brand_SurfExampleSite" tests="1" failures="1" timestamp="26 Sep 2014 20:34:10 GMT" time="0.001" errors="0">
  <testcase name="memberUndelete_SurfExampleSite" time="0.001" classname="com.nbcuni.test.nbcidx.member.undelete.brands.TC5085_MemberUndelete_Brand_SurfExampleSite">
    <failure type="java.lang.AssertionError" message="com.mongodb.MongoException$Network: IOException authenticating the connection">
      <![CDATA[java.lang.AssertionError: com.mongodb.MongoException$Network: IOException authenticating the connection
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at com.nbcuni.test.nbcidx.member.undelete.brands.TC5086_MemberUndelete_Brand_IDXAPIExplorer.startEnvironment(TC5086_MemberUndelete_Brand_IDXAPIExplorer.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- memberUndelete_SurfExampleSite -->
</testsuite> <!-- com.nbcuni.test.nbcidx.member.undelete.brands.TC5085_MemberUndelete_Brand_SurfExampleSite -->
